### ISSUE TITLE
Pre-trained on IN-21K

### ISSUE THREAD

**Issue by WangYZ1608** [facebookresearch/maws#10]
Hi @mannatsingh, @QuentinDuval, congratulations for the great work.

Can you tell me the model size pre-trained on IN21K and fine-tune image size (It doesn't look like 224) in Table. 21?

Also, would you mind sharing the weights of MAE pre-trained on IN21K?

Thanks. 
Looking forward to your reply.

**Comment by WangYZ1608** [comment]
> Hi @mannatsingh, @QuentinDuval, congratulations for the great work.
> 
> Can you tell me the model size pre-trained on IN21K and fine-tune image size (It doesn't look like 224) in Table. 21?
> 
> Also, would you mind sharing the weights of MAE pre-trained on IN21K?
> 
> Thanks. Looking forward to your reply.

Oh, I didn't look closely the caption of Table. 21, the model-size is ViT-L.

**Comment by mannatsingh** [comment]
Hi @WangYZ1608 thank you, glad you find the work useful. 

The latest version of the paper on arxiv (https://arxiv.org/abs/2303.13496) has the details about resolution, it is 512px. 

I will have to check if the weights are still available. Will get back to you next week.

**Comment by WangYZ1608** [comment]
> Hi @WangYZ1608 thank you, glad you find the work useful.
> 
> The latest version of the paper on arxiv (https://arxiv.org/abs/2303.13496) has the details about resolution, it is 512px.
> 
> I will have to check if the weights are still available. Will get back to you next week.

Thanks for your reply.

**Comment by WangYZ1608** [comment]
> @WangYZ1608 sorry for the delay but I was out sick. The IN21k checkpoint has been added to the repo in [8fd8599](https://github.com/facebookresearch/maws/commit/8fd85999c07d761259fb597a66ce7a5cfe2ceaf4)

Please take care and get well soon. Thanks for your reply.
